articles/urls.py
from django.urls import path
from .views import (
    ArticleListView,
    ArticleUpdateView,
    ArticleDeleteView,
    ArticleDetailView,
    ArticleCreateView,
)

app_name='articles'
urlpatterns = [
    path('<int:pk>/edit/', ArticleUpdateView.as_view(), name='edit'),
    path('<int:pk>/detail/', ArticleDetailView.as_view(), name='detail'),
    path('<int:pk>/delete/', ArticleDeleteView.as_view(), name='delete'),
    path('new/', ArticleCreateView.as_view(), name='new'),
    path('', ArticleListView.as_view(), name='article_list'),
]

newspaper_project/urls.py
from django.contrib import admin
from django.urls import path, include
#from django.views.generic.base import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('users/', include('django.contrib.auth.urls')),
    #path('', TemplateView.as_view(template_name='users/home.html'), name='home'),
    path('', include('pages.urls')),
    path('articles/', include('articles.urls')),
]

pages/urls.py
from django.urls import path
from .views import HomePageView

app_name='pages'
urlpatterns = [
    path('', HomePageView.as_view(), name='home'),
]

users/urls.py
from django.urls import path
from .views import SignUpView

app_name='users'
urlpatterns = [
    path('signup/', SignUpView.as_view(), name='signup'),
]

articles/models.py
from django.db import models
from django.urls import reverse
from django.conf import settings
from django.contrib.auth import get_user_model

# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length=255)
    body = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(
        get_user_model(),
        on_delete = models.CASCADE,
    )

    def __str__(self):
        return f'{self.title}'

    def get_absolute_url(self):
        return reverse('articles:detail', args=[str(self.id)])

class Comment(models.Model):
    article = models.ForeignKey(
        Article, on_delete=models.CASCADE,
        related_name = 'comments',
        )
    comment = models.CharField(max_length=150)
    author = models.ForeignKey(
        get_user_model(),
        on_delete = models.CASCADE,
    )

    def __str__(self):
        return self.comment

    def get_absolute_url(self):
        return reverse('articles:article_list')

pages/models.py
from django.db import models

# Create your models here.

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.

class CustomUser(AbstractUser):
    age = models.PositiveIntegerField(null=True, blank=True)

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import CustomUser

class CustomUserCreationForm(UserCreationForm):

    class Meta(UserCreationForm.Meta):
        model = CustomUser
        #fields = UserCreationForm.Meta.fields + ('age',)
        fields = ('username', 'email', 'age', )

class CustomUserChangeForm(UserChangeForm):

    class Meta:
        model = CustomUser
        #fields = UserChangeForm.Meta.fields
        fields = ('username', 'email', 'age', )

articles/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import PermissionDenied
from django.views.generic import ListView, DetailView
from django.views.generic.edit import UpdateView, DeleteView, CreateView
from django.urls import reverse_lazy

from .models import Article

# Create your views here.
class ArticleListView(LoginRequiredMixin, ListView):
    model = Article
    template_name = 'articles/article_list.html'
    login_url = 'login'

class ArticleDetailView(LoginRequiredMixin, DetailView):
    model = Article
    template_name = 'articles/article_detail.html'
    login_url = 'login'

class ArticleUpdateView(LoginRequiredMixin, UpdateView):
    model = Article
    fields = ('title', 'body')
    template_name = 'articles/article_edit.html'
    login_url = 'login'

    def dispatch(self, request, *args, **kwargs):
        obj = self.get_object()
        if obj.author != self.request.user:
            raise PermissionDenied
        return super().dispatch(request, *args, **kwargs)

class ArticleDeleteView(LoginRequiredMixin, DeleteView):
    model = Article
    template_name = 'articles/article_delete.html'
    success_url = reverse_lazy('articles:article_list')
    login_url = 'login'

    def dispatch(self, request, *args, **kwargs):
        obj = self.get_object()
        if obj.author != self.request.user:
            raise PermissionDenied
        return super().dispatch(request, *args, **kwargs)

class ArticleCreateView(LoginRequiredMixin, CreateView):
    model = Article
    template_name = 'articles/article_create.html'
    fields = ('title', 'body')
    login_url = 'login'

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

pages/views.py
from django.views.generic import TemplateView
# Create your views here.

class HomePageView(TemplateView):
    template_name = 'users/home.html'

users/views.py
from django.urls import reverse_lazy
from django.views.generic import CreateView

from .forms import CustomUserCreationForm

# Create your views here.

class SignUpView(CreateView):
    form_class = CustomUserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'users/signup.html'

templates/articles/article_create.html
{% extends 'base.html' %}

{% block content %}
<h1>New Article</h1>
<form method='post' action=''>
  {% csrf_token %}
  {{ form.as_p }}
  <button class='btn btn-success ml-2', type='submit'>Save</button>
</form>
{% endblock content %}

templates/articles/article_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete</h1>
  <form method='post' action=''>
    {% csrf_token %}
    <p>Are you sure want to delete "{{ article.title }}"?</p>
    <button class="btn btn-danger ml-2" type='submit'>Conform</button>
  </form>
{% endblock %}

templates/articles/article_detail.html
{% extends 'base.html' %}

{% block content %}
  <div class="article-entry">
    <h2>{{ object.title }}</h2>
    <p>by {{ object.author }} | {{ object.date }}</p>
    <p>{{ object.body }}</p>
  </div>
  <p><a href="{% url 'articles:edit' article.pk %}">Edit</a> |
    <a href="{% url 'articles:delete' article.pk %}">Delete</a>
  </p>
  <p>Back to <a href="{% url 'articles:article_list' %}">All Articles</a>.</p>
{% endblock content %}

templates/articles/article_edit.html
{% extends 'base.html' %}

{% block content %}
  <h1>Edit</h1>
  <form action='' method='post'>
    {% csrf_token %}
    {{ form.as_p }}
    <button class='btn btn-info ml-2' type='submit'>Update</button>
  </form>
{% endblock content %}

templates/articles/article_list.html
{% extends 'base.html' %}

{% block title %}Articles{% endblock title %}

{% block content %}
{% for article in object_list %}
  <div class="card">
    <div class="card-header">
        <span class="font-weight-bold">{{ article.title }}</span> &middot;
        <span class="text-muted">by {{ article.author }} |
          {{ article.date }}
        </span>
        <div class="card-body">
          <p>{{ article.body }}</p>
          <a class="btn btn-success" href="{% url 'articles:edit' article.pk %}">Edit</a> |
          <a class="btn btn-danger" href="{% url 'articles:delete' article.pk %}">Delete</a>
        </div>
        <div class="card-footer">
          {% for comment in article.comments.all %}
            <p>
              <span class="font-weight-bold">{{ comment.author }} &middot;</span>
              {{ comment }}
            </p>
          {% endfor %}
        </div>
    </div>
    <br />
  </div>
{% endfor %}
{% endblock content %}

templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,
    initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
    integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <title>{% block title %}Newspaper App{% endblock title %}</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4">
      <a class="navbar-brand" href="{% url 'pages:home' %}">Newspaper</a>
      {% if user.is_authenticated %}
        <ul class="navbar-nav mr-auto">
          <li class="nav-item"><a href="{% url 'articles:new' %}">+ New</a></li>
        </ul>
      {% endif %}
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse"
        aria-controls="navbarCollapse"
        aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggle-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarCollapse">
        {% if user.is_authenticated %}
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <a class="nav-link dropdown-toggle" href="#" id="userMenu" data-toggle="dropdown" aria-haspopup="true"
                aria-expanded="false">
                {{ user.username }}
              </a>
              <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userMenu">
                <a class="dropdown-item" href="{% url 'password_change' %}">Change password</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="{% url 'logout' %}">Log Out</a>
              </div>
            </li>
          </ul>
        {% else %}
          <form class="form-inline ml-auto">
            <a href="{% url 'login' %}" class="btn btn-online-secondary">Log In</a>
            <a href="{% url 'users:signup' %}" class="btn btn-primary ml-2">Sign up</a>
          </form>
        {% endif %}
      </div>
    </nav>

    <div class="container">
      {% block content %}
      {% endblock content %}
    </div>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
      integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
      crossorigin="anonymous">
    </script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
      integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
      crossorigin="anonymous">
    </script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
      integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
      crossorigin="anonymous">
    </script>
  </body>
</html>

templates/users/home.html
{% extends 'base.html' %}

{% block title %}Home{% endblock title %}

{% block content %}
<div class="jumbotron">
  <h1 class="display-4">Newspaper app</h1>
  <p class="lead">A Newspaper website built with Django.</p>
  <p class='lead'>
    <a class="btn btn-primary btn-lg" href="{% url 'articles:article_list' %}" role="button">View All Articles</a>
  </p>
</div>
{% endblock content %}

templates/users/signup.html
{% extends 'base.html' %}

{% block title %}Sign Up{% endblock title %}

{% block content %}
<h2>Sign Up</h2>
<form action="" method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <button class="btn btn-success" type='submit'>Sign Up</button>
</form>
{% endblock content %}